trigger:
  paths:
    include:
      - terraform/infrastructure/**

pool:
  name: self-hosted-k8s
  vmImage: "ubuntu-latest"

variables:
  # Define your backend S3 bucket and key here
  terraform_backend_bucket: "backend-s3-final-project"
  terraform_backend_key: "eks/terraform.tfstate"
  terraform_region: "us-east-1"
  aws_service_connection: "terraform" # Replace with your Actual Service Connection Name

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: "latest"

  - task: TerraformTask@4
    displayName: "Terraform Init"
    inputs:
      provider: "aws"
      command: "init"
      workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/infrastructure"
      backendServiceAWS: "$(aws_service_connection)"
      backendAWSBucketName: "$(terraform_backend_bucket)"
      backendAWSKey: "$(terraform_backend_key)"
      backendAWSRegion: "$(terraform_region)"

  - task: TerraformTask@4
    displayName: "Terraform Validate"
    inputs:
      provider: "aws"
      command: "validate"
      workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/infrastructure"

  - task: TerraformTask@4
    displayName: "Terraform Plan"
    inputs:
      provider: "aws"
      command: "plan"
      workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/infrastructure"
      environmentServiceNameAWS: "$(aws_service_connection)"

 