trigger:
  paths:
    include:
      - terraform/infrastructure/**

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: "vault token and ip"
  - name: terraform_backend_bucket
    value: "backend-s3-final-project"
  - name: terraform_backend_key
    value: "infra/terraform.tfstate"
  - name: terraform_region
    value: "us-east-1"
  - name: aws_service_connection
    value: "terraform"

parameters:
  - name: action
    displayName: "Terraform Action"
    type: string
    default: "apply"
    values:
      - apply
      - destroy

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: "latest"

  - task: TerraformTaskV4@4
    displayName: "Terraform Init"
    inputs:
      provider: "aws"
      command: "init"
      workingDirectory: "$(System.DefaultWorkingDirectory)/final-project-nti/terraform/infrastructure"
      backendServiceAWS: "$(aws_service_connection)"
      backendAWSBucketName: "$(terraform_backend_bucket)"
      backendAWSKey: "$(terraform_backend_key)"
      backendAWSRegion: "$(terraform_region)"

  - task: TerraformTaskV4@4
    displayName: "Terraform Validate"
    inputs:
      provider: "aws"
      command: "validate"
      workingDirectory: "$(System.DefaultWorkingDirectory)/final-project-nti/terraform/infrastructure"

  # Plan only runs on apply (not destroy)
  - ${{ if eq(parameters.action, 'apply') }}:
      - task: TerraformTaskV4@4
        displayName: "Terraform Plan"
        inputs:
          provider: "aws"
          command: "plan"
          workingDirectory: "$(System.DefaultWorkingDirectory)/final-project-nti/terraform/infrastructure"
          environmentServiceNameAWS: "$(aws_service_connection)"
          commandOptions: '-var="vault_addr=http://$(vault-ip):8200" -var="vault_token=$(vault-token)"'

  - task: TerraformTaskV4@4
    displayName: "Terraform ${{ parameters.action }}"
    inputs:
      provider: "aws"
      command: "${{ parameters.action }}"
      workingDirectory: "$(System.DefaultWorkingDirectory)/final-project-nti/terraform/infrastructure"
      environmentServiceNameAWS: "$(aws_service_connection)"
      commandOptions: '-auto-approve -var="vault_addr=http://$(vault-ip):8200" -var="vault_token=$(vault-token)"'
