trigger:
  paths:
    include:
      - terraform/tools/**

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: "vault token and ip"
  - name: terraform_backend_bucket
    value: "backend-s3-final-project"
  - name: terraform_backend_key
    value: "tools/terraform.tfstate"
  - name: terraform_region
    value: "us-east-1"
  - name: aws_service_connection
    value: "terraform"

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: "latest"

  # 1. Terraform Tools Deployment
  - task: TerraformTaskV4@4
    displayName: "Terraform Init"
    inputs:
      provider: "aws"
      command: "init"
      workingDirectory: "$(System.DefaultWorkingDirectory)/final-project-nti/terraform/tools"
      backendServiceAWS: "$(aws_service_connection)"
      backendAWSBucketName: "$(terraform_backend_bucket)"
      backendAWSKey: "$(terraform_backend_key)"
      backendAWSRegion: "$(terraform_region)"

  - task: TerraformTaskV4@4
    displayName: "Terraform Plan & Apply"
    inputs:
      provider: "aws"
      command: "apply" # Use apply with auto-approve for automation
      workingDirectory: "$(System.DefaultWorkingDirectory)/final-project-nti/terraform/tools"
      environmentServiceNameAWS: "$(aws_service_connection)"
      commandOptions: >
        -auto-approve 
        -var="vault_addr=http://$(vault-ip):8200" 
        -var="vault_token=$(vault-token)" 
        -var="azuredevops_agent_image=mcr.microsoft.com/azure-pipelines/vsts-agent:ubuntu-20.04"

  # 2. Extract Infrastructure Info & Deploy K8s
  - task: AWSShellScript@1
    displayName: "K8s Deployment Logic"
    inputs:
      awsServiceConnection: "$(awsCredentials)"
      regionName: "$(terraform_region)"
      scriptType: "inline"
      inlineScript: |
        set -e

        # Update Kubeconfig
        aws eks update-kubeconfig --region $(terraform_region) --name final-project-cluster

        # Get the Target Group ARN from the OTHER state file
        # We use AWS CLI or Terraform to fetch this
        cd $(System.DefaultWorkingDirectory)/final-project-nti/terraform/infrastructure

        terraform init \
          -backend-config="bucket=$(terraform_backend_bucket)" \
          -backend-config="key=infrastructure/terraform.tfstate" \
          -backend-config="region=$(terraform_region)"

        TARGET_GROUP_ARN=$(terraform output -raw nlb_target_group_arn)

        cd ../../ # Back to project root

        # Replace Placeholders in K8s Manifests
        sed -i "s|REPLACEMENT_IMAGE_URL|mcr.microsoft.com/azure-pipelines/vsts-agent:ubuntu-20.04|g" k8s/azuredevops-keda.yaml

        if [ -z "$TARGET_GROUP_ARN" ]; then
          echo "Error: TARGET_GROUP_ARN is empty. Check your infrastructure state."
          exit 1
        fi

        sed -i "s|TARGET_GROUP_ARN_PLACEHOLDER|$TARGET_GROUP_ARN|g" k8s/nginx-tgb.yaml

        # Deploy to EKS
        kubectl apply -f k8s/azuredevops-keda.yaml
        kubectl apply -f k8s/nginx-tgb.yaml
