trigger:
  paths:
    include:
      - terraform/tools/**

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: "vault token and ip"
  - name: terraform_backend_bucket
    value: "backend-s3-final-project"
  - name: terraform_backend_key
    value: "tools/terraform.tfstate"
  - name: terraform_region
    value: "us-east-1"
  - name: aws_service_connection
    value: "terraform"

parameters:
  - name: action
    displayName: "Terraform Action"
    type: string
    default: "apply"
    values:
      - apply
      - destroy

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: "latest"

  # 1. Terraform Init
  - task: TerraformTaskV4@4
    displayName: "Terraform Init"
    inputs:
      provider: "aws"
      command: "init"
      workingDirectory: "$(System.DefaultWorkingDirectory)/final-project-nti/terraform/tools"
      backendServiceAWS: "$(aws_service_connection)"
      backendAWSBucketName: "$(terraform_backend_bucket)"
      backendAWSKey: "$(terraform_backend_key)"
      backendAWSRegion: "$(terraform_region)"

  # 2. Terraform Validate
  - task: TerraformTaskV4@4
    displayName: "Terraform Validate"
    inputs:
      provider: "aws"
      command: "validate"
      workingDirectory: "$(System.DefaultWorkingDirectory)/final-project-nti/terraform/tools"

  # 3. Terraform Apply or Destroy (based on parameter)
  - task: TerraformTaskV4@4
    displayName: "Terraform ${{ parameters.action }}"
    inputs:
      provider: "aws"
      command: "${{ parameters.action }}"
      workingDirectory: "$(System.DefaultWorkingDirectory)/final-project-nti/terraform/tools"
      environmentServiceNameAWS: "$(aws_service_connection)"
      commandOptions: >
        -auto-approve 
        -var="vault_addr=http://$(vault-ip):8200" 
        -var="vault_token=$(vault-token)" 
        -var="azuredevops_agent_image=mcr.microsoft.com/azure-pipelines/vsts-agent:ubuntu-20.04"

  # K8s manifests are now applied via Terraform-native resources in k8s_manifests.tf
